name: Docker

on:
    workflow_dispatch:
    push:
        paths:
            - 'deps/Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fmiexchange.jl

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set branch tags and metadata
        id: dockertag
        shell: bash
        env:
            REFNAME: ${{ github.head_ref || github.ref_name }}
            ACTOR: ${{ github.actor }}
            REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
            if [ $REFNAME == "main" ]
            then
                echo "DOCKERTAG=latest" >> $GITHUB_ENV;
                echo "IMAGE_PREFIX=$REPOSITORY_OWNER" >> $GITHUB_ENV;
            else
                echo "DOCKERTAG=$REFNAME" >> $GITHUB_ENV;
                echo "IMAGE_PREFIX=$ACTOR" >> $GITHUB_ENV;
            fi

      - id: lowercasetag
        name: Make the docker url lower case
        uses: ASzc/change-string-case-action@v1
        with:
            string: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}:${{ env.DOCKERTAG }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: deps/Dockerfile
          push: true
          tags: ${{ steps.lowercasetag.outputs.lowercase }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
